### ISSUE TITLE
Bug2 ( Why u get 2 Jack Daniels after defeating the second monster ??? )

### ISSUE THREAD

**Issue by Kapejko** [Red-Pi/KDC-Base#32] opened 2019-11-27 16:30 UTC
After defeating the second monster you get 2 jack daniels...

**Comment by Red-Pi** [comment] 2019-11-27 18:20
I think I need more information than that :D
What is the output of the game?
What are the steps to get to this Bug?

**Comment by Red-Pi** [comment] 2019-11-27 18:50
I couldn't reproduce this, sorry.

**Comment by Red-Pi** [comment] 2019-11-27 18:51
Working on #33, #34 and #31 will probably fix this.

**Comment by Red-Pi** [comment] 2019-11-27 19:15
Hopfully fixed with Merge #36 - please test

**Comment by Red-Pi** [comment] 2019-11-28 07:54
Presumably fixed

**Closed by Red-Pi** 2019-11-28 07:54 UTC
Labels: bug, duplicate, question, wontfix
